language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: $SSH_HOST

install:
  - yarn

script:
  - commitlint-travis
  - yarn test:coverage

before_deploy:
  - openssl aes-256-cbc -K $encrypted_94b97748e151_key -iv $encrypted_94b97748e151_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - yarn build:docs
  - yarn build:app

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    keep_history: true
    local_dir: docs
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: master
