language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - commitlint-travis
  - yarn test:coverage

before_deploy:
  - if ! [[ $TRAVIS_DOCS ]]; then
      export TRAVIS_DOCS="1.$TRAVIS_BUILD_NUMBER" &&
      yarn build:docs;
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    keep_history: true
    local_dir: docs
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: master
