language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - commitlint-travis

jobs:
  stages:
    - test
    - docs
    - deploy
  include:
    # running testings
    - stage: test
      script:
        - yarn test:coverage

    # deploy docs to github pages
    - stage: docs
      script:
        - yarn build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: '$GITHUB_TOKEN'
        keep_history: true
        local_dir: docs
        on:
          branch: master

    - stage: deploy
      provider: script
      skip_cleanup: true
      script:
        - echo $SSH_KEY >> $HOME/.ssh/known_hosts
        - openssl aes-256-cbc -K $encrypted_94b97748e151_key -iv $encrypted_94b97748e151_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
        - bash deploy.sh
      on:
        branch: master
